/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package addTasks;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.ScanRequest;
import com.amazonaws.services.dynamodbv2.model.ScanResult;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Library {
    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "taskmaster";
    private Regions REGION = Regions.US_WEST_2;

    public List<Task> getAllTask(){
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);
        return ddbMapper.scan(Task.class, new DynamoDBScanExpression());
    }

    public List<Task> getUserTasks(Task task){
        HashMap<String, AttributeValue> eav = new HashMap<>();
        eav.put(":v1", new AttributeValue().withS(task.getAssignee()));
        DynamoDBScanExpression scanExpression = new DynamoDBScanExpression()
                .withFilterExpression("assignee = :v1")
                .withExpressionAttributeValues(eav);

        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);
        return ddbMapper.scan(Task.class, scanExpression);
    }

    public Task createTask(Task task){
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        Task t = new Task(task.getTitle(), task.getDescription(), task.getAssignee());
        if(task.getAssignee() == null){
            History history = new History("Task was created and is not assigned");
            t.addToHistory(history);
        } else {
            t.setAssignee(task.getAssignee());
            t.setStatus("assigned");
            History history = new History("Task was created and assigned to " + task.getAssignee());
            t.addToHistory(history);
        }

        ddbMapper.save(t);

        return task;
    }

    public Task deleteTask(Task task){
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        Task t = ddbMapper.load(Task.class, task.getId());
        ddbMapper.delete(t);
        return t;
    }

    public Task updateAssignee(Task task){
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        Task t = ddbMapper.load(Task.class, task.getId());
        t.setAssignee(task.getAssignee());
        t.setStatus("assigned");
        t.addToHistory(new History("assigned"));
        ddbMapper.save(t);
        return t;
    }

    public Task updateStatus(Task task){
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        Task t = ddbMapper.load(Task.class, task.getId());
        String status = t.getStatus();

        if(t.getAssignee() != null){
            switch(status){
                case "available":
                    t.setStatus("assigned");
                    History history = new History("Task was assigned to " + t.getAssignee());
                    t.addToHistory(history);
                    break;

                case "assigned":
                    t.setStatus("accepted");
                    History history2 = new History("Task was accepted by " + t.getAssignee());
                    t.addToHistory(history2);
                    break;

                case "accepted":
                    t.setStatus("finished");
                    History history3 = new History("Task was finished by " + t.getAssignee());
                    t.addToHistory(history3);
                    t.setStatus("finished");
            }
            ddbMapper.save(t);
        }

        return task;
    }
}
